Format workflows and switch to mcOS 26 xlarge

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -2,10 +2,10 @@ name: Format
 
 on:
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request_target:
     types:
-      - labeled 
+      - labeled
 
 jobs:
   format:
@@ -16,59 +16,59 @@ jobs:
 
     name: Lint and format
     steps:
-    - name: Checkout for internal PR
-      if: ${{ github.event.pull_request.head.repo.owner.login == github.repository_owner }}
-      uses: actions/checkout@v5
-      with:
-        # Use PAT which has write access
-        token: ${{ secrets.PAT }}
-        ref: ${{ github.head_ref }}
+      - name: Checkout for internal PR
+        if: ${{ github.event.pull_request.head.repo.owner.login == github.repository_owner }}
+        uses: actions/checkout@v5
+        with:
+          # Use PAT which has write access
+          token: ${{ secrets.PAT }}
+          ref: ${{ github.head_ref }}
 
-    - name: Checkout for external PR
-      if: ${{ github.event.pull_request.head.repo.owner.login != github.repository_owner }}
-      uses: actions/checkout@v5
+      - name: Checkout for external PR
+        if: ${{ github.event.pull_request.head.repo.owner.login != github.repository_owner }}
+        uses: actions/checkout@v5
 
-    - name: Format
-      run: swift format --in-place --parallel --recursive Sources/ Tests/
-    
-    - name: Check for formatting changes
-      id: check_changes
-      run: |
-        git diff --exit-code
-      continue-on-error: true
+      - name: Format
+        run: swift format --in-place --parallel --recursive Sources/ Tests/
 
-    - name: Check if PR has a specific label
-      id: check_label
-      uses: actions/github-script@v8
-      with:
-        result-encoding: string
-        script: |
-          const labelToCheck = 'auto-format';
-          const prLabels = context.payload.pull_request.labels.map(label => label.name);
-          return prLabels.includes(labelToCheck);
+      - name: Check for formatting changes
+        id: check_changes
+        run: |
+          git diff --exit-code
+        continue-on-error: true
 
-    - name: Apply auto-formatting
-      if: >
-        steps.check_changes.outcome == 'failure' &&
-        steps.check_label.outputs.result == 'true' &&
-        github.event.pull_request.head.repo.owner.login == github.repository_owner
-      uses: stefanzweifel/git-auto-commit-action@v7
-      with:
-        commit_message: Apply auto-formatting
+      - name: Check if PR has a specific label
+        id: check_label
+        uses: actions/github-script@v8
+        with:
+          result-encoding: string
+          script: |
+            const labelToCheck = 'auto-format';
+            const prLabels = context.payload.pull_request.labels.map(label => label.name);
+            return prLabels.includes(labelToCheck);
 
-    - name: Fail if changes detected (optional)
-      if: >
-        steps.check_changes.outcome == 'failure' &&
-        (
-          github.event.pull_request.head.repo.owner.login != github.repository_owner || 
-          steps.check_label.outputs.result == 'false'
-        )
-      run: |
-        echo "::error::Formatting issues detected. Please fix them."
-        echo "Run 'swift format --in-place --parallel --recursive Sources/ Tests/' locally to fix formatting."
-        exit 1
+      - name: Apply auto-formatting
+        if: >
+          steps.check_changes.outcome == 'failure' &&
+          steps.check_label.outputs.result == 'true' &&
+          github.event.pull_request.head.repo.owner.login == github.repository_owner
+        uses: stefanzweifel/git-auto-commit-action@v7
+        with:
+          commit_message: Apply auto-formatting
 
-    - name: Lint
-      id: lint 
-      run: |
-        swift format lint --strict --parallel --recursive Sources/ Tests/
+      - name: Fail if changes detected (optional)
+        if: >
+          steps.check_changes.outcome == 'failure' &&
+          (
+            github.event.pull_request.head.repo.owner.login != github.repository_owner || 
+            steps.check_label.outputs.result == 'false'
+          )
+        run: |
+          echo "::error::Formatting issues detected. Please fix them."
+          echo "Run 'swift format --in-place --parallel --recursive Sources/ Tests/' locally to fix formatting."
+          exit 1
+
+      - name: Lint
+        id: lint
+        run: |
+          swift format lint --strict --parallel --recursive Sources/ Tests/
